swagger: '2.0'
info:
  version: 1.0.0
  title: emprendo API-Gateway
  description: API Gateway para los servicios de usuario y emprendimiento
schemes:
  - https
produces:
  - application/json
paths:
  /login:
    post:
      summary: Iniciar sesión
      operationId: login
      x-google-backend:
        address: http://127.0.0.1:8080
      parameters:
        - in: body
          name: body
          description: Datos de inicio de sesión
          required: true
          schema:
            type: object
            properties:
              token:
                type: string
                example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
      responses:
        200:
          description: Inicio de sesión exitoso
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: true
              uid:
                type: string
                example: abc123
              email:
                type: string
                example: john.doe@example.com
              nombre:
                type: string
                example: John Doe
              tipo:
                type: string
                example: admin
        404:
          description: Usuario no encontrado
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              message:
                type: string
                example: Usuario no encontrado
        401:
          description: No autorizado
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              message:
                type: string
                example: Unauthorized

  /register:
    post:
      summary: Registrar un nuevo usuario
      operationId: register
      x-google-backend:
        address: http://127.0.0.1:8080
      parameters:
        - in: body
          name: body
          description: Datos de registro
          required: true
          schema:
            type: object
            properties:
              id:
                type: string
                example: abc123
              nombre:
                type: string
                example: John Doe
              email:
                type: string
                format: email
                example: john.doe@example.com
              password:
                type: string
                format: password
                example: securepassword123
              tipo:
                type: string
                example: admin
              tipoAuth:
                type: integer
                example: 0
      responses:
        200:
          description: Registro exitoso
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: true
              message:
                type: string
                example: Usuario registrado exitosamente
        400:
          description: Error en la solicitud
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              message:
                type: string
                example: Ingrese un Correo Electrónico válido

  /user/info:
    get:
      summary: Obtener información del usuario
      operationId: getInfo
      x-google-backend:
        address: http://127.0.0.1:8080
      parameters:
        - in: query
          name: userId
          type: string
          required: true
          description: ID del usuario
      responses:
        200:
          description: Información del usuario obtenida exitosamente
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: true
              user:
                type: object
                properties:
                  nombre:
                    type: string
                    example: John Doe
                  email:
                    type: string
                    example: john.doe@example.com
                  tipo:
                    type: string
                    example: admin
        404:
          description: Usuario no encontrado
          schema:
            type: object
            properties:
              message:
                type: string
                example: Usuario no encontrado

  /emprendimiento/emprendimientoInfo:
    get:
      summary: Obtener información del emprendimiento
      operationId: emprendimientoInfo
      x-google-backend:
        address: https://emprendimiento-service-26932749356.us-west1.run.app      
      parameters:
        - in: query
          name: idEmprendimiento
          type: string
          required: true
          description: ID del emprendimiento
      responses:
        200:
          description: Información del emprendimiento obtenida exitosamente
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: true
              emprendimientoData:
                type: object
                properties:
                  nombreComercial:
                    type: string
                    example: Mi Emprendimiento
                  localizacion:
                    type: string
                    example: Ciudad, País
                  ruc:
                    type: string
                    example: 1234567890
        404:
          description: Emprendimiento no encontrado
          schema:
            type: object
            properties:
              message:
                type: string
                example: Emprendimiento no encontrado
        400:
          description: Falta el parámetro idEmprendimiento
          schema:
            type: object
            properties:
              message:
                type: string
                example: Falta el parámetro idEmprendimiento

  /emprendimiento/guardarEmprendimiento:
    post:
      summary: Guardar datos del emprendimiento
      operationId: emprendimientoRegister
      x-google-backend:
        address: https://emprendimiento-service-26932749356.us-west1.run.app   
      parameters:
        - in: body
          name: body
          description: Datos del emprendimiento
          required: true
          schema:
            type: object
            properties:
              idEmprendedor:
                type: string
                example: 123
              nombreComercial:
                type: string
                example: Mi Emprendimiento
              localizacion:
                type: string
                example: Ciudad, País
              ruc:
                type: string
                example: 1234567890
      responses:
        200:
          description: Guardado de datos exitoso
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: true
              message:
                type: string
                example: Guardado de datos exitoso
        400:
          description: Error en la solicitud
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              message:
                type: string
                example: Error al guardar los datos

  /emprendimiento/emprendimientos:
    get:
      summary: Obtener los mejores emprendimientos
      operationId: emprendimientosInfo
      x-google-backend:
        address: https://emprendimiento-service-26932749356.us-west1.run.app   
      responses:
        200:
          description: Lista de los mejores emprendimientos obtenida exitosamente
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: true
              emprendimientos:
                type: array
                items:
                  type: object
                  properties:
                    nombreComercial:
                      type: string
                      example: Mi Emprendimiento
                    localizacion:
                      type: string
                      example: Ciudad, País
                    ruc:
                      type: string
                      example: 1234567890
        500:
          description: Error interno del servidor
          schema:
            type: object
            properties:
              message:
                type: string
                example: Error interno del servidor
              success:
                type: boolean
                example: false